# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_digits/blk_mem_gen_digits.xci
# IP: The module: 'blk_mem_gen_digits' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_digits/blk_mem_gen_digits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_digits'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_digits/blk_mem_gen_digits.xci
# IP: The module: 'blk_mem_gen_digits' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_digits/blk_mem_gen_digits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_digits'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
