# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.cache/wt} [current_project]
set_property parent.project_path {D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/res/test_0.coe}}
add_files {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/res/weights.coe}}
add_files {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/res/00.coe}}
add_files {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/res/00-56x56.coe}}
add_files {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/res/background.coe}}
add_files {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/res/dirt.coe}}
add_files {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/res/digits.coe}}
add_files {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/res/stone.coe}}
add_files {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/res/grass.coe}}
add_files {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/res/cursor.coe}}
add_files {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/res/pickaxe.coe}}
add_files {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/res/normalpen.coe}}
add_files {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/res/normaleraser.coe}}
read_verilog -library xil_defaultlib {
  {D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/new/CanvasPainter.v}
  {D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/new/DigitMultiplier.v}
  {D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/imports/mouse_demo/Mouse.v}
  {D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/new/MouseAddrGen.v}
  {D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/new/canvas_mem_addr_gen.v}
  {D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/new/clock_divisor.v}
  {D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/new/neural_net.v}
  {D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/new/pixel_gen.v}
  {D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/new/seven-segment-display.v}
  {D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/new/vga.v}
  {D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/new/top.v}
}
read_vhdl -library xil_defaultlib {
  {D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/imports/mouse_demo/MouseCtl.vhd}
  {D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/imports/mouse_demo/Ps2Interface.vhd}
}
read_ip -quiet {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_img/blk_mem_gen_img.xci}}
set_property used_in_implementation false [get_files -all {{d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_img/blk_mem_gen_img_ooc.xdc}}]

read_ip -quiet {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc}}]

read_ip -quiet {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_const/blk_mem_gen_const.xci}}
set_property used_in_implementation false [get_files -all {{d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_const/blk_mem_gen_const_ooc.xdc}}]

read_ip -quiet {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_inter/blk_mem_gen_inter.xci}}
set_property used_in_implementation false [get_files -all {{d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_inter/blk_mem_gen_inter_ooc.xdc}}]

read_ip -quiet {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_bg_img/blk_mem_gen_bg_img.xci}}
set_property used_in_implementation false [get_files -all {{d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_bg_img/blk_mem_gen_bg_img_ooc.xdc}}]

read_ip -quiet {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_dirt/blk_mem_gen_dirt.xci}}
set_property used_in_implementation false [get_files -all {{d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_dirt/blk_mem_gen_dirt_ooc.xdc}}]

read_ip -quiet {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_stone/blk_mem_gen_stone.xci}}
set_property used_in_implementation false [get_files -all {{d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_stone/blk_mem_gen_stone_ooc.xdc}}]

read_ip -quiet {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_grass/blk_mem_gen_grass.xci}}
set_property used_in_implementation false [get_files -all {{d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_grass/blk_mem_gen_grass_ooc.xdc}}]

read_ip -quiet {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_digits/blk_mem_gen_digits.xci}}
set_property used_in_implementation false [get_files -all {{d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_digits/blk_mem_gen_digits_ooc.xdc}}]

read_ip -quiet {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_cursor/blk_mem_gen_cursor.xci}}
set_property used_in_implementation false [get_files -all {{d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_cursor/blk_mem_gen_cursor_ooc.xdc}}]

read_ip -quiet {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_eraser/blk_mem_gen_eraser.xci}}
set_property used_in_implementation false [get_files -all {{d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_eraser/blk_mem_gen_eraser_ooc.xdc}}]

read_ip -quiet {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_normalpen/blk_mem_gen_normalpen.xci}}
set_property used_in_implementation false [get_files -all {{d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_normalpen/blk_mem_gen_normalpen_ooc.xdc}}]

read_ip -quiet {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_normaleraser/blk_mem_gen_normaleraser.xci}}
set_property used_in_implementation false [get_files -all {{d:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/sources_1/ip/blk_mem_gen_normaleraser/blk_mem_gen_normaleraser_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/constrs_1/new/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{D:/j3soon/File/Projects/Clean Projects/Handwritten-Digit-Recognition-Painter/src/Handwritten-Digit-Recognition-Painter.srcs/constrs_1/new/Basys3_Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
